### ISSUE TITLE
无法复制带有标题的word内容

### ISSUE THREAD

**Issue by MiracleLau** [ChurchTao/clipboard-rs#48]
### The problem | 问题描述

**环境：**
系统：MacOS13.5
Word：Office365

监听rtf的变化时，如果在word中复制的内容带有标题，则会提示：
```
start watch!
thread 'main' panicked at src/main.rs:19:47:
called `Result::unwrap()` on an `Err` value: "No string found"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1102:23
   4: <clipbord_test::Manager as clipboard_rs::common::ClipboardHandler>::on_clipboard_change
             at ./src/main.rs:19:22
   5: <clipboard_rs::platform::macos::ClipboardWatcherContext<T> as clipboard_rs::ClipboardWatcher<T>>::start_watch::{{closure}}
             at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clipboard-rs-0.2.1/src/platform/macos.rs:80:26
   6: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/slice/iter/macros.rs:252:21
   7: <clipboard_rs::platform::macos::ClipboardWatcherContext<T> as clipboard_rs::ClipboardWatcher<T>>::start_watch
             at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clipboard-rs-0.2.1/src/platform/macos.rs:78:5
   8: clipbord_test::main
             at ./src/main.rs:42:2
   9: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

代码如下：
```
use clipboard_rs::{
	Clipboard, ClipboardContext, ClipboardHandler, ClipboardWatcher, ClipboardWatcherContext,
};
use std::{thread, time::Duration};

struct Manager {
	ctx: ClipboardContext,
}

impl Manager {
	pub fn new() -> Self {
		let ctx = ClipboardContext::new().unwrap();
		Manager { ctx }
	}
}

impl ClipboardHandler for Manager {
	fn on_clipboard_change(&mut self) {
        let result = self.ctx.get_rich_text().unwrap();
		println!(
			"on_clipboard_change, txt = {}",
			&result
		);
        let _ = self.ctx.set_rich_text(result);
	}
}

fn main() {
	let manager = Manager::new();

	let mut watcher = ClipboardWatcherContext::new().unwrap();

	let watcher_shutdown = watcher.add_handler(manager).get_shutdown_channel();

	thread::spawn(move || {
		// thread::sleep(Duration::from_secs(5));
		// println!("stop watch!");
		// watcher_shutdown.stop();
	});

	println!("start watch!");
	watcher.start_watch();
}
```
复制的内容如下：
<img width="687" alt="图片" src="https://github.com/user-attachments/assets/98baf92a-1c25-449c-81ec-3ecae2d7c025">

请问应该如何解决。

### Release version | 版本

0.2.1

### Operating system | 操作系统

MacOS13.5

### Logs | 日志

start watch!
thread 'main' panicked at src/main.rs:19:47:
called `Result::unwrap()` on an `Err` value: "No string found"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/result.rs:1102:23
   4: <clipbord_test::Manager as clipboard_rs::common::ClipboardHandler>::on_clipboard_change
             at ./src/main.rs:19:22
   5: <clipboard_rs::platform::macos::ClipboardWatcherContext<T> as clipboard_rs::ClipboardWatcher<T>>::start_watch::{{closure}}
             at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clipboard-rs-0.2.1/src/platform/macos.rs:80:26
   6: <core::slice::iter::IterMut<T> as core::iter::traits::iterator::Iterator>::for_each
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/slice/iter/macros.rs:252:21
   7: <clipboard_rs::platform::macos::ClipboardWatcherContext<T> as clipboard_rs::ClipboardWatcher<T>>::start_watch
             at /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clipboard-rs-0.2.1/src/platform/macos.rs:78:5
   8: clipbord_test::main
             at ./src/main.rs:42:2
   9: core::ops::function::FnOnce::call_once
             at /rustc/3f5fd8dd41153bc5fdca9427e9e05be2c767ba23/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by ChurchTao** [comment]
收到 这个问题之前发现过，主要是word的格式可能有点特殊 我找时间看下

**Comment by MiracleLau** [comment]
> 收到 这个问题之前发现过，主要是word的格式可能有点特殊 我找时间看下

好的好的，感谢~
